/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package registro;

/**
 *
 * @author Gustavo
 */
public class FormularioRegistro extends java.awt.Frame {

    /**
     * Creates new form FormularioRegistro
     */
    public FormularioRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new java.awt.Label();
        labelNombre = new java.awt.Label();
        labelEdad = new java.awt.Label();
        labelCarrera = new java.awt.Label();
        labelDuracion = new java.awt.Label();
        labelArancel = new java.awt.Label();
        labelRamosAprobados = new java.awt.Label();
        textFieldNombre = new java.awt.TextField();
        textFieldEdad = new java.awt.TextField();
        textFieldCarrera = new java.awt.TextField();
        textFieldDuracion = new java.awt.TextField();
        textFieldArancel = new java.awt.TextField();
        textFieldRamosAprobados = new java.awt.TextField();
        buttonEnviar = new java.awt.Button();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setTitle("Formulario de Registro de Alumnos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelTitulo.setText("FORMULARIO DE REGISTRO DE ALUMNOS");

        labelNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNombre.setText("Nombre:");

        labelEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelEdad.setText("Edad:");

        labelCarrera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCarrera.setText("Carrera:");

        labelDuracion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDuracion.setText("Duracion Carrera:");

        labelArancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelArancel.setText("Arancel Carrera:");

        labelRamosAprobados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelRamosAprobados.setText("Ramos Aprobados:");

        textFieldNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });

        textFieldEdad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEdadActionPerformed(evt);
            }
        });

        textFieldCarrera.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCarreraActionPerformed(evt);
            }
        });

        textFieldDuracion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDuracionActionPerformed(evt);
            }
        });

        textFieldArancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldArancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldArancelActionPerformed(evt);
            }
        });

        textFieldRamosAprobados.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldRamosAprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldRamosAprobadosActionPerformed(evt);
            }
        });

        buttonEnviar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonEnviar.setLabel("ENVIAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelArancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRamosAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldArancel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(textFieldDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(textFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(textFieldEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(textFieldRamosAprobados, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(buttonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(602, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(labelCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(labelDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelArancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelRamosAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textFieldArancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldRamosAprobados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void textFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEdadActionPerformed
        // TODO add your handling code here:
        int edad = Integer.parseInt(textFieldNombre.getText());
    }//GEN-LAST:event_textFieldEdadActionPerformed

    private void textFieldCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCarreraActionPerformed
        // TODO add your handling code here:
        String carrera = textFieldCarrera.getText();
    }//GEN-LAST:event_textFieldCarreraActionPerformed

    private void textFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDuracionActionPerformed
        // TODO add your handling code here:
        int edad = Integer.parseInt(textFieldDuracion.getText());
    }//GEN-LAST:event_textFieldDuracionActionPerformed

    private void textFieldArancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldArancelActionPerformed
        // TODO add your handling code here:
        int arancel = Integer.parseInt(textFieldArancel.getText());
    }//GEN-LAST:event_textFieldArancelActionPerformed

    private void textFieldRamosAprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldRamosAprobadosActionPerformed
        // TODO add your handling code here:
        int ramosAprobados = Integer.parseInt(textFieldRamosAprobados.getText());
    }//GEN-LAST:event_textFieldRamosAprobadosActionPerformed

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
        String nombre = textFieldNombre.getText();
        
    }//GEN-LAST:event_textFieldNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioRegistro().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button buttonEnviar;
    private java.awt.Label labelArancel;
    private java.awt.Label labelCarrera;
    private java.awt.Label labelDuracion;
    private java.awt.Label labelEdad;
    private java.awt.Label labelNombre;
    private java.awt.Label labelRamosAprobados;
    private java.awt.Label labelTitulo;
    private java.awt.TextField textFieldArancel;
    private java.awt.TextField textFieldCarrera;
    private java.awt.TextField textFieldDuracion;
    private java.awt.TextField textFieldEdad;
    private java.awt.TextField textFieldNombre;
    private java.awt.TextField textFieldRamosAprobados;
    // End of variables declaration//GEN-END:variables
}
