/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package puntodeventa;

/**
 *
 * @author Gustavo
 */
public class Interfaz extends java.awt.Frame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        // Agregar opciones al choice
        choicePagos.add("Efectivo");
        choicePagos.add("Débito");
        choicePagos.add("Crédito");
        
        // Inicialización de variables
        int total = 0;
        int subtotal = 0;
        
        // TODO
        /*
            1. Metodos, getters & setters.
            2. Ventana aparte para ingresar items a inventario disponible al sistema.
            3. Mejorar la visual.
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button9 = new java.awt.Button();
        button8 = new java.awt.Button();
        button7 = new java.awt.Button();
        button6 = new java.awt.Button();
        button5 = new java.awt.Button();
        button4 = new java.awt.Button();
        button3 = new java.awt.Button();
        button2 = new java.awt.Button();
        button1 = new java.awt.Button();
        button0 = new java.awt.Button();
        buttonPunto = new java.awt.Button();
        buttonCE = new java.awt.Button();
        labelItem = new java.awt.Label();
        labelCantidad = new java.awt.Label();
        labelPrecio = new java.awt.Label();
        listItems = new java.awt.List();
        buttonItem18 = new java.awt.Button();
        buttonItem17 = new java.awt.Button();
        buttonItem16 = new java.awt.Button();
        buttonItem15 = new java.awt.Button();
        buttonItem14 = new java.awt.Button();
        buttonItem13 = new java.awt.Button();
        buttonItem12 = new java.awt.Button();
        buttonItem11 = new java.awt.Button();
        buttonItem10 = new java.awt.Button();
        buttonItem9 = new java.awt.Button();
        buttonItem8 = new java.awt.Button();
        buttonItem7 = new java.awt.Button();
        buttonItem6 = new java.awt.Button();
        buttonItem5 = new java.awt.Button();
        buttonItem4 = new java.awt.Button();
        buttonItem3 = new java.awt.Button();
        buttonItem2 = new java.awt.Button();
        buttonItem1 = new java.awt.Button();
        labelPagos = new java.awt.Label();
        choicePagos = new java.awt.Choice();
        labelIVA = new java.awt.Label();
        textFieldIVA = new java.awt.TextField();
        labelTotal = new java.awt.Label();
        textFieldTotal = new java.awt.TextField();
        labelSubTotal = new java.awt.Label();
        textFieldSubTotal = new java.awt.TextField();
        labelEfectivo = new java.awt.Label();
        textFieldEfectivo = new java.awt.TextField();
        labelCambio = new java.awt.Label();
        textFieldCambio = new java.awt.TextField();
        buttonPagar = new java.awt.Button();
        buttonReset = new java.awt.Button();
        buttonEliminar = new java.awt.Button();
        buttonImprimir = new java.awt.Button();
        buttonSalir = new java.awt.Button();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setTitle("Punto de Venta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        button9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button9.setLabel("9");

        button8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button8.setLabel("8");

        button7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button7.setLabel("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button6.setLabel("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button5.setLabel("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button4.setLabel("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button3.setLabel("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button2.setLabel("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button1.setLabel("1");

        button0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        button0.setLabel("0");

        buttonPunto.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonPunto.setLabel(".");

        buttonCE.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        buttonCE.setLabel("CE");

        labelItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelItem.setText("Item");

        labelCantidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelCantidad.setText("Cantidad");

        labelPrecio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPrecio.setText("Precio");

        listItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listItemsActionPerformed(evt);
            }
        });

        buttonItem18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem18ActionPerformed(evt);
            }
        });

        buttonItem17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem17ActionPerformed(evt);
            }
        });

        buttonItem16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem16ActionPerformed(evt);
            }
        });

        buttonItem15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem15ActionPerformed(evt);
            }
        });

        buttonItem14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem14ActionPerformed(evt);
            }
        });

        buttonItem13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem13ActionPerformed(evt);
            }
        });

        buttonItem12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem12ActionPerformed(evt);
            }
        });

        buttonItem11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem11ActionPerformed(evt);
            }
        });

        buttonItem10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem10ActionPerformed(evt);
            }
        });

        buttonItem9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem9ActionPerformed(evt);
            }
        });

        buttonItem8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem8ActionPerformed(evt);
            }
        });

        buttonItem7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem7ActionPerformed(evt);
            }
        });

        buttonItem6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem6ActionPerformed(evt);
            }
        });

        buttonItem5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem5ActionPerformed(evt);
            }
        });

        buttonItem4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem4ActionPerformed(evt);
            }
        });

        buttonItem3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem3ActionPerformed(evt);
            }
        });

        buttonItem2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem2ActionPerformed(evt);
            }
        });

        buttonItem1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonItem1ActionPerformed(evt);
            }
        });

        labelPagos.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelPagos.setText("Método de Pago");

        choicePagos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelIVA.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelIVA.setText("IVA 19%");

        textFieldIVA.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        labelTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelTotal.setText("Total");

        textFieldTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        labelSubTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelSubTotal.setText("SubTotal");

        textFieldSubTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        labelEfectivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelEfectivo.setText("Efectivo");

        textFieldEfectivo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        labelCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        labelCambio.setText("Cambio");

        textFieldCambio.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        buttonPagar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonPagar.setLabel("Pagar");
        buttonPagar.setName(""); // NOI18N

        buttonReset.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonReset.setLabel("Reset");
        buttonReset.setName(""); // NOI18N

        buttonEliminar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonEliminar.setLabel("Eliminar");
        buttonEliminar.setName(""); // NOI18N

        buttonImprimir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonImprimir.setLabel("Imprimir");
        buttonImprimir.setName(""); // NOI18N

        buttonSalir.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        buttonSalir.setLabel("Salir");
        buttonSalir.setName(""); // NOI18N
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(listItems, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(103, 103, 103)
                                    .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonItem13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonItem7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(buttonItem12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(labelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(choicePagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(buttonItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(buttonItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(buttonItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(textFieldEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(121, 121, 121)
                                                .addComponent(textFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(buttonItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(buttonItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(buttonSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(buttonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttonCE, buttonPunto});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonEliminar, buttonImprimir, buttonPagar, buttonReset});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1)
                            .addComponent(listItems, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonItem13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonItem7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(choicePagos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldIVA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {button0, button1, button2, button3, button4, button5, button6, button7, button8, button9, buttonCE, buttonPunto});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonEliminar, buttonImprimir, buttonPagar, buttonReset});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void buttonItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem13ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 13                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem13ActionPerformed

    private void buttonItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem14ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 14                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem14ActionPerformed

    private void buttonItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem15ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 15                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem15ActionPerformed

    private void buttonItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem16ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 16                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem16ActionPerformed

    private void buttonItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem17ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 17                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem17ActionPerformed

    private void buttonItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem18ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 18                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem18ActionPerformed

    private void buttonItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem7ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 7                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem7ActionPerformed

    private void buttonItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem8ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 8                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem8ActionPerformed

    private void buttonItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem9ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 9                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem9ActionPerformed

    private void buttonItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem10ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 10                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem10ActionPerformed

    private void buttonItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem11ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 11                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem11ActionPerformed

    private void buttonItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem12ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 12                     1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem12ActionPerformed

    private void buttonItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem3ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 3                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem3ActionPerformed

    private void buttonItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem6ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 6                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem6ActionPerformed

    private void buttonItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem1ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 1                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem1ActionPerformed

    private void buttonItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem5ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 5                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem5ActionPerformed

    private void buttonItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem2ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 2                       1              $2.990");
        valorProducto = 2990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem2ActionPerformed

    private void buttonItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonItem4ActionPerformed
        // TODO add your handling code here:
        listItems.add("Item 4                       1              $1.990");
        valorProducto = 1990;
        total += valorProducto;
    }//GEN-LAST:event_buttonItem4ActionPerformed

    private void listItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listItemsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_listItemsActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button0;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Button buttonCE;
    private java.awt.Button buttonEliminar;
    private java.awt.Button buttonImprimir;
    private java.awt.Button buttonItem1;
    private java.awt.Button buttonItem10;
    private java.awt.Button buttonItem11;
    private java.awt.Button buttonItem12;
    private java.awt.Button buttonItem13;
    private java.awt.Button buttonItem14;
    private java.awt.Button buttonItem15;
    private java.awt.Button buttonItem16;
    private java.awt.Button buttonItem17;
    private java.awt.Button buttonItem18;
    private java.awt.Button buttonItem2;
    private java.awt.Button buttonItem3;
    private java.awt.Button buttonItem4;
    private java.awt.Button buttonItem5;
    private java.awt.Button buttonItem6;
    private java.awt.Button buttonItem7;
    private java.awt.Button buttonItem8;
    private java.awt.Button buttonItem9;
    private java.awt.Button buttonPagar;
    private java.awt.Button buttonPunto;
    private java.awt.Button buttonReset;
    private java.awt.Button buttonSalir;
    private java.awt.Choice choicePagos;
    private java.awt.Label labelCambio;
    private java.awt.Label labelCantidad;
    private java.awt.Label labelEfectivo;
    private java.awt.Label labelIVA;
    private java.awt.Label labelItem;
    private java.awt.Label labelPagos;
    private java.awt.Label labelPrecio;
    private java.awt.Label labelSubTotal;
    private java.awt.Label labelTotal;
    private java.awt.List listItems;
    private java.awt.TextField textFieldCambio;
    private java.awt.TextField textFieldEfectivo;
    private java.awt.TextField textFieldIVA;
    private java.awt.TextField textFieldSubTotal;
    private java.awt.TextField textFieldTotal;
    // End of variables declaration//GEN-END:variables
    float iva;
    int valorProducto;
    int total;
    int subtotal;
}
